// Map geometry for the two terrain regions. No contour data is loaded at
// runtime: sizes, bounds, stops and elevations come from terrain-data.ts
// (generated by scripts/relief.mjs).
//
// Coordinates are map units with EAST UP (the drive runs bottom → top):
//   x = north → south across the width, y = east → west down the height.
//   route     420 × 1241, the whole drive (Bay Area → Mammoth)
//   eastside  520 × 527,  Tioga Pass, Mono Basin, June Lake, Mammoth (detail)
import { EAST_TO_ROUTE, REGIONS } from './terrain-data';

export type Region = keyof typeof REGIONS;
export type Pt = readonly [number, number];
/** SVG viewBox as [x, y, width, height] in map units. */
export type Crop = readonly [number, number, number, number];

export { REGIONS, EAST_TO_ROUTE };

export type StopKey = keyof typeof REGIONS.route.stops;

/** Display names for the stops. */
export const STOP_NAMES: Record<StopKey, string> = {
  bayarea: 'Bay Area',
  oakdale: 'Oakdale',
  groveland: 'Groveland',
  craneflat: 'Crane Flat',
  olmsted: 'Olmsted Point',
  tenaya: 'Tenaya Lake',
  tuolumne: 'Tuolumne Meadows',
  tioga: 'Tioga Pass',
  leevining: 'Lee Vining',
  monolake: 'Mono Lake',
  southtufa: 'South Tufa',
  lundy: 'Lundy Canyon',
  conway: 'Conway Summit',
  junelake: 'June Lake',
  mammoth: 'Mammoth Lakes',
  convict: 'Convict Lake',
  hotcreek: 'Hot Creek',
};

/** Latitude/longitude → map units for a region. */
export function project(region: Region, lat: number, lon: number): Pt {
  const R = REGIONS[region];
  const b = R.bounds;
  return [((b.north - lat) / (b.north - b.south)) * R.width, ((b.east - lon) / (b.east - b.west)) * R.height];
}

/** Map units → latitude/longitude. */
export function unproject(region: Region, [x, y]: Pt): { lat: number; lon: number } {
  const R = REGIONS[region];
  const b = R.bounds;
  return { lat: b.north - (x / R.width) * (b.north - b.south), lon: b.east - (y / R.height) * (b.east - b.west) };
}

/** A stop's position in a region (undefined if the stop is outside it). */
export function stop(region: Region, key: StopKey): Pt | undefined {
  return (REGIONS[region].stops as Record<string, Pt | undefined>)[key];
}

/** A stop's ground elevation in meters (from the elevation tiles). */
export function stopElevation(key: StopKey): number {
  return REGIONS.route.stopElevation[key];
}

export const feet = (m: number) => Math.round(m * 3.28084);

// Published elevations win over the tile-derived ones where signs exist.
const SIGNED_FEET: Partial<Record<StopKey, number>> = { tioga: 9945 };
/** A stop's elevation in feet, using the signed value when there is one ("9,945 ft"). */
export const stopFeet = (key: StopKey) => SIGNED_FEET[key] ?? feet(stopElevation(key));
/** "9,945 ft" */
export const fmtFeet = (m: number) => `${feet(m).toLocaleString('en-US')} ft`;

/** eastside units → route units (affine; both are linear projections). */
export function eastToRoute([x, y]: Pt): Pt {
  const [a, , , d, e, f] = EAST_TO_ROUTE;
  return [a * x + e, d * y + f];
}
/** route units → eastside units. */
export function routeToEast([x, y]: Pt): Pt {
  const [a, , , d, e, f] = EAST_TO_ROUTE;
  return [(x - e) / a, (y - f) / d];
}
/** SVG transform that draws eastside content on the route map. */
export const EAST_TO_ROUTE_TRANSFORM = `matrix(${EAST_TO_ROUTE.join(' ')})`;

/** The eastside's footprint on the route map, as a crop. */
export const EASTSIDE_IN_ROUTE: Crop = (() => {
  const [x0, y0] = eastToRoute([0, 0]);
  const [x1, y1] = eastToRoute([REGIONS.eastside.width, REGIONS.eastside.height]);
  return [x0, y0, x1 - x0, y1 - y0];
})();

/**
 * A crop centered on a point, `width` map units wide at the given aspect
 * (width / height), kept inside the region.
 */
export function cropAround(region: Region, [cx, cy]: Pt, width: number, aspect: number): Crop {
  const R = REGIONS[region];
  const w = Math.min(width, R.width);
  const h = Math.min(w / aspect, R.height);
  const x = Math.max(0, Math.min(R.width - w, cx - w / 2));
  const y = Math.max(0, Math.min(R.height - h, cy - h / 2));
  return [x, y, w, h];
}

/** Smooth path (centripetal-ish Catmull-Rom) through points, as SVG path data. */
export function splinePath(pts: readonly Pt[], tension = 0.5): string {
  if (pts.length < 2) return '';
  const f = (n: number) => n.toFixed(1);
  const p = [pts[0], ...pts, pts[pts.length - 1]];
  let d = `M${f(pts[0][0])} ${f(pts[0][1])}`;
  for (let i = 1; i < p.length - 2; i++) {
    const [p0, p1, p2, p3] = [p[i - 1], p[i], p[i + 1], p[i + 2]];
    const c1 = [p1[0] + ((p2[0] - p0[0]) / 6) * tension * 2, p1[1] + ((p2[1] - p0[1]) / 6) * tension * 2];
    const c2 = [p2[0] - ((p3[0] - p1[0]) / 6) * tension * 2, p2[1] - ((p3[1] - p1[1]) / 6) * tension * 2];
    d += ` C${f(c1[0])} ${f(c1[1])} ${f(c2[0])} ${f(c2[1])} ${f(p2[0])} ${f(p2[1])}`;
  }
  return d;
}

/**
 * Friday's drive on the route map: the real stop coordinates, plus two US-395
 * waypoints south of Lee Vining (June Lake Junction, the CA-203 turnoff).
 * The JSON has stops, not road geometry, so this is a smooth approximation.
 */
export const FRIDAY_DRIVE: readonly Pt[] = [
  ...(['bayarea', 'oakdale', 'groveland', 'craneflat', 'olmsted', 'tenaya', 'tuolumne', 'tioga', 'leevining'] as const).map((k) => REGIONS.route.stops[k] as Pt),
  project('route', 37.807, -119.071),
  project('route', 37.655, -118.935),
  REGIONS.route.stops.mammoth as Pt,
];

/** The same Friday drive on the eastside map, from Olmsted Point on. */
export const FRIDAY_DRIVE_EAST: readonly Pt[] = [
  ...(['olmsted', 'tenaya', 'tuolumne', 'tioga', 'leevining'] as const).map((k) => REGIONS.eastside.stops[k] as Pt),
  project('eastside', 37.807, -119.071),
  project('eastside', 37.655, -118.935),
  REGIONS.eastside.stops.mammoth as Pt,
];
