// Generated by scripts/relief.mjs from art/topo/*.json. Do not edit.
// Coordinates are map units, EAST IS UP: x runs north→south across the
// width, y runs east→west down the height (the drive goes bottom → top).
export const REGIONS = {
  "route": {
    "width": 420,
    "height": 1241,
    "bounds": {
      "west": -122.25,
      "east": -118.7,
      "south": 37.25,
      "north": 38.2
    },
    "levels": [
      0,
      100,
      250,
      400,
      550,
      700,
      850,
      1000,
      1150,
      1300,
      1450,
      1600,
      1750,
      1900,
      2050,
      2200,
      2350,
      2500,
      2650,
      2800,
      2950,
      3100,
      3250,
      3400,
      3550,
      3700,
      3850,
      4000,
      4150
    ],
    "stops": {
      "bayarea": [
        331.6,
        1153.6
      ],
      "oakdale": [
        191.4,
        750.5
      ],
      "groveland": [
        159.6,
        535.6
      ],
      "craneflat": [
        197.6,
        384.9
      ],
      "olmsted": [
        172,
        274.8
      ],
      "tenaya": [
        164,
        264.3
      ],
      "tuolumne": [
        144.6,
        230
      ],
      "tioga": [
        127.8,
        195.1
      ],
      "leevining": [
        107.4,
        147.5
      ],
      "monolake": [
        84,
        111.9
      ],
      "southtufa": [
        115.8,
        114.3
      ],
      "lundy": [
        76.5,
        188.8
      ],
      "conway": [
        50,
        169.5
      ],
      "junelake": [
        185.2,
        131.1
      ],
      "mammoth": [
        244,
        95.1
      ],
      "convict": [
        268.4,
        53.5
      ],
      "hotcreek": [
        238.3,
        44
      ]
    },
    "stopElevation": {
      "bayarea": -3,
      "oakdale": 49,
      "groveland": 877,
      "craneflat": 1904,
      "olmsted": 2554,
      "tenaya": 2634,
      "tuolumne": 2627,
      "tioga": 3033,
      "leevining": 2072,
      "monolake": 1947,
      "southtufa": 1956,
      "lundy": 2373,
      "conway": 2491,
      "junelake": 2370,
      "mammoth": 2405,
      "convict": 2322,
      "hotcreek": 2156
    }
  },
  "eastside": {
    "width": 520,
    "height": 527,
    "bounds": {
      "west": -119.55,
      "east": -118.78,
      "south": 37.55,
      "north": 38.15
    },
    "levels": [
      1900,
      1960,
      2020,
      2080,
      2140,
      2200,
      2260,
      2320,
      2380,
      2440,
      2500,
      2560,
      2620,
      2680,
      2740,
      2800,
      2860,
      2920,
      2980,
      3040,
      3100,
      3160,
      3220,
      3280,
      3340,
      3400,
      3460,
      3520,
      3580,
      3640,
      3700,
      3760,
      3820,
      3880,
      3940,
      4000
    ],
    "stops": {
      "olmsted": [
        293.8,
        483.2
      ],
      "tenaya": [
        278.2,
        462.7
      ],
      "tuolumne": [
        240.1,
        395.6
      ],
      "tioga": [
        207.1,
        327.2
      ],
      "leevining": [
        167.3,
        234.1
      ],
      "monolake": [
        121.3,
        164.3
      ],
      "southtufa": [
        183.7,
        169.1
      ],
      "lundy": [
        106.6,
        314.8
      ],
      "conway": [
        54.6,
        277.2
      ],
      "junelake": [
        319.8,
        201.9
      ],
      "mammoth": [
        435.1,
        131.4
      ],
      "convict": [
        482.7,
        50
      ],
      "hotcreek": [
        423.8,
        31.5
      ]
    },
    "stopElevation": {
      "olmsted": 2578,
      "tenaya": 2575,
      "tuolumne": 2617,
      "tioga": 3034,
      "leevining": 2069,
      "monolake": 1943,
      "southtufa": 1959,
      "lundy": 2380,
      "conway": 2497,
      "junelake": 2332,
      "mammoth": 2401,
      "convict": 2311,
      "hotcreek": 2157
    }
  }
} as const;

/** SVG matrix(a b c d e f) mapping eastside units into route units. */
export const EAST_TO_ROUTE = [0.51012,0,0,0.51077,22.10526,27.9662] as const;

/** Relief raster resolution (pixels per map unit) per region and theme. */
export const RELIEF_SCALE = {"route":{"light":5,"dark":5,"night":2.5},"eastside":{"light":6,"dark":6,"night":4}} as const;

/** Relief tiles per region and theme, in map units (they overlap by 2 px). */
export const RELIEF_TILES = {"route":{"light":[{"f":"relief-route-light-0.webp","x":0,"y":0,"w":420,"h":414},{"f":"relief-route-light-1.webp","x":0,"y":413.2,"w":420,"h":414.6},{"f":"relief-route-light-2.webp","x":0,"y":827,"w":420,"h":414}],"dark":[{"f":"relief-route-dark-0.webp","x":0,"y":0,"w":420,"h":414},{"f":"relief-route-dark-1.webp","x":0,"y":413.2,"w":420,"h":414.6},{"f":"relief-route-dark-2.webp","x":0,"y":827,"w":420,"h":414}],"night":[{"f":"relief-route-night-0.webp","x":0,"y":0,"w":420,"h":1241.2}]},"eastside":{"light":[{"f":"relief-eastside-light-0.webp","x":0,"y":0,"w":260.333,"h":263.833},{"f":"relief-eastside-light-1.webp","x":259.667,"y":0,"w":260.333,"h":263.833},{"f":"relief-eastside-light-2.webp","x":0,"y":263.167,"w":260.333,"h":263.833},{"f":"relief-eastside-light-3.webp","x":259.667,"y":263.167,"w":260.333,"h":263.833}],"dark":[{"f":"relief-eastside-dark-0.webp","x":0,"y":0,"w":260.333,"h":263.833},{"f":"relief-eastside-dark-1.webp","x":259.667,"y":0,"w":260.333,"h":263.833},{"f":"relief-eastside-dark-2.webp","x":0,"y":263.167,"w":260.333,"h":263.833},{"f":"relief-eastside-dark-3.webp","x":259.667,"y":263.167,"w":260.333,"h":263.833}],"night":[{"f":"relief-eastside-night-0.webp","x":0,"y":0,"w":520,"h":527}]}} as const;
