// Icons. Phosphor (regular 1.5 px at 24 matches Inter's stems):
//   regular for everything, `weight="fill"` for the active tab and primary
//   glyphs, `weight="bold"` at 16 px inside chips so tiny glyphs don't go thin.
// Sizes: 24 tab bar, 20 buttons, 18 icon wells, 16 chips/meta, 13 inline meta.
// Import icons from here (not from the package) so the set stays small and
// consistent. Need one that isn't listed? Ask the foundation to add it.
export type { Icon, IconProps, IconWeight } from '@phosphor-icons/react';
export {
  // navigation and chrome
  SunHorizon,
  CalendarDots,
  Compass,
  Leaf,
  BookOpenText,
  GearSix,
  CaretLeft,
  CaretRight,
  CaretDown,
  CaretUp,
  X,
  XCircle,
  Check,
  CheckCircle,
  Circle,
  Plus,
  Minus,
  ArrowRight,
  ArrowLeft,
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  ArrowSquareOut,
  ArrowsClockwise,
  ArrowCounterClockwise,
  ArrowBendUpLeft,
  DotsThree,
  MagnifyingGlass,
  Funnel,
  Trash,
  Eye,
  Lock,
  Info,
  Question,
  Warning,
  WarningCircle,
  WifiSlash,
  WifiHigh,
  DownloadSimple,
  Export,
  ShareNetwork,
  Link,
  DeviceMobile,
  SquaresFour,
  Rows,
  TextAa,
  SpeakerHigh,
  SpeakerSlash,
  Bell,
  // travel
  NavigationArrow,
  MapPin,
  MapTrifold,
  CarSimple,
  CarProfile,
  GasPump,
  RoadHorizon,
  Barricade,
  TrafficCone,
  Signpost,
  Path,
  Clock,
  Timer,
  Hourglass,
  House,
  Bed,
  Toilet,
  Storefront,
  Ticket,
  CurrencyDollar,
  Phone,
  Globe,
  Backpack,
  ListChecks,
  NotePencil,
  Notebook,
  // outdoors and weather
  Mountains,
  Tree,
  TreeEvergreen,
  Park,
  Plant,
  Flower,
  Tent,
  Campfire,
  Thermometer,
  ThermometerSimple,
  Sun,
  SunDim,
  CloudSun,
  Cloud,
  CloudRain,
  CloudMoon,
  Snowflake,
  Wind,
  Drop,
  Waves,
  Fire,
  Flashlight,
  Moon,
  MoonStars,
  Star,
  ShootingStar,
  Planet,
  Sparkle,
  Binoculars,
  Footprints,
  PawPrint,
  Bird,
  Fish,
  Butterfly,
  // food
  Coffee,
  ForkKnife,
  BowlFood,
  Hamburger,
  IceCream,
  Cookie,
  Cake,
  // kids and play
  Lightbulb,
  Camera,
  Image,
  PaintBrush,
  Palette,
  PencilSimple,
  GameController,
  PuzzlePiece,
  Shapes,
  Smiley,
  Shuffle,
  Play,
  Pause,
  Stop,
  Ruler,
  Target,
  Crosshair,
  Flag,
  Gift,
  MusicNotes,
  Users,
  User,
  UserCircle,
  // faith
  Heart,
  HandHeart,
  HandsPraying,
  BookOpen,
  BookBookmark,
  Bookmark,
  Church,
} from '@phosphor-icons/react';

export { MapsDiamond, Car, LeafMark, LeafPip } from './glyphs';
