// Pre-render the lit terrain so the app never rasterizes huge contour SVGs at
// runtime. For each region (route, eastside) and theme (light, dark, night):
//   public/img/topo/relief-<region>-<theme>.webp
// and the small data module the app uses instead of the 590 KB contour JSON:
//   src/art/terrain-data.ts  (sizes, bounds, stops, elevations, levels)
//
// Source contours: art/topo/*.json (from scripts/topo.mjs; not shipped).
// Usage: npm run relief     (needs the preinstalled Playwright Chromium)
//        node scripts/relief.mjs --data-only
//
// The relief is Tanaka "illuminated contours": each elevation band is filled
// from a hypsometric ramp, and copies shifted toward/away from the sun leave a
// lit sliver on slopes facing it and a shaded sliver on the others.
//   light  sunrise from the east (top of the map); calm: half the offset and
//          sliver strength of the prototype, hairline index contours carry it
//   dark   evening sun from the west (bottom); dimmer slivers, fills at ~60%
//   night  red-shifted and dim, for night vision
// Mono Lake is drawn as water: inside the 1,900 m surface, outside 1,960 m.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const load = (n) => JSON.parse(readFileSync(join(root, 'art/topo', n + '.json'), 'utf8'));
const route = load('route');
const east = load('eastside');

// ---------------------------------------------------------------------------
// Data module

const f2 = (n) => Math.round(n * 100) / 100;

// Raster resolution (px per map unit) and tile grid [cols, rows].
const SCALE = { route: { light: 5, dark: 5, night: 2.5 }, eastside: { light: 6, dark: 6, night: 4 } };
const GRID = { route: { light: [1, 3], dark: [1, 3], night: [1, 1] }, eastside: { light: [2, 2], dark: [2, 2], night: [1, 1] } };
const OVERLAP = 2; // px on each inner edge, so tile seams never show
const SIZE = { route: [route.width, route.height], eastside: [east.width, east.height] };
/** Pixel rects (and unit rects) of each tile. */
function tileRects(name, theme) {
  const k = SCALE[name][theme];
  const [uw, uh] = SIZE[name];
  const W = Math.round(uw * k), H = Math.round(uh * k);
  const [cols, rows] = GRID[name][theme];
  const out = [];
  for (let r = 0; r < rows; r++)
    for (let c = 0; c < cols; c++) {
      const x0 = Math.max(0, Math.round((c * W) / cols) - (c ? OVERLAP : 0));
      const x1 = Math.min(W, Math.round(((c + 1) * W) / cols) + (c < cols - 1 ? OVERLAP : 0));
      const y0 = Math.max(0, Math.round((r * H) / rows) - (r ? OVERLAP : 0));
      const y1 = Math.min(H, Math.round(((r + 1) * H) / rows) + (r < rows - 1 ? OVERLAP : 0));
      out.push({ px: [x0, y0, x1 - x0, y1 - y0], i: out.length, W, H, k });
    }
  return out;
}
const r3 = (n) => Math.round(n * 1000) / 1000;
function tilesFor() {
  const o = {};
  for (const name of ['route', 'eastside']) {
    o[name] = {};
    for (const theme of ['light', 'dark', 'night']) {
      o[name][theme] = tileRects(name, theme).map((t) => {
        const [x, y, w, h] = t.px;
        return { f: `relief-${name}-${theme}-${t.i}.webp`, x: r3(x / t.k), y: r3(y / t.k), w: r3(w / t.k), h: r3(h / t.k) };
      });
    }
  }
  return o;
}
function regionData(T) {
  return {
    width: T.width,
    height: T.height,
    bounds: T.bounds,
    levels: T.levels,
    stops: Object.fromEntries(Object.entries(T.stops).map(([k, [x, y]]) => [k, [f2(x), f2(y)]])),
    stopElevation: T.stopElevation,
  };
}
// eastside → route: both are linear east-up projections of lat/lon.
//   route.x = (Nr - lat) / (Nr - Sr) * Wr ;  lat = Ne - ex/We * (Ne - Se)
const R = route.bounds, E = east.bounds;
const ax = (route.width / (R.north - R.south)) * ((E.north - E.south) / east.width);
const bx = (route.width / (R.north - R.south)) * (R.north - E.north);
const ay = (route.height / (R.east - R.west)) * ((E.east - E.west) / east.height);
const by = (route.height / (R.east - R.west)) * (R.east - E.east);
const E2R = [ax, 0, 0, ay, bx, by].map((n) => Math.round(n * 1e5) / 1e5);

const dataTs = `// Generated by scripts/relief.mjs from art/topo/*.json. Do not edit.
// Coordinates are map units, EAST IS UP: x runs north→south across the
// width, y runs east→west down the height (the drive goes bottom → top).
export const REGIONS = ${JSON.stringify({ route: regionData(route), eastside: regionData(east) }, null, 2)} as const;

/** SVG matrix(a b c d e f) mapping eastside units into route units. */
export const EAST_TO_ROUTE = ${JSON.stringify(E2R)} as const;

/** Relief raster resolution (pixels per map unit) per region and theme. */
export const RELIEF_SCALE = ${JSON.stringify(SCALE)} as const;

/** Relief tiles per region and theme, in map units (they overlap by 2 px). */
export const RELIEF_TILES = ${JSON.stringify(tilesFor(), null, 0)} as const;
`;
writeFileSync(join(root, 'src/art/terrain-data.ts'), dataTs);
console.log('wrote src/art/terrain-data.ts');
if (process.argv.includes('--data-only')) process.exit(0);

// ---------------------------------------------------------------------------
// Palettes

const hex = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const mix = (a, b, t) => {
  const A = hex(a), B = hex(b);
  return '#' + A.map((v, i) => Math.round(v + (B[i] - v) * t).toString(16).padStart(2, '0')).join('');
};
function ramp(stops, t) {
  for (let i = 1; i < stops.length; i++) {
    if (t <= stops[i][0]) {
      const [t0, c0] = stops[i - 1], [t1, c1] = stops[i];
      return mix(c0, c1, (t - t0) / (t1 - t0));
    }
  }
  return stops[stops.length - 1][1];
}

const PAL = {
  light: {
    bg: '#f4eee5',
    water: '#d3e0e2',
    shore: 'rgba(79,103,112,0.35)',
    ramp: [[0, '#f5efe6'], [0.3, '#f2e9dd'], [0.55, '#ede0cf'], [0.75, '#e8d4bb'], [0.9, '#e5c7a4'], [1, '#e2b98c']],
    lit: [255, 255, 255], litMin: 0.28, litMax: 0.5,
    shade: 'rgba(122,72,30,0.13)',
    index: 'rgba(110,70,30,0.26)', indexW: 0.9, // px at raster scale
    shift: 0.45, sun: -1,
  },
  dark: {
    bg: '#0e0a07',
    water: '#0e181c',
    shore: 'rgba(142,163,170,0.25)',
    ramp: [[0, '#100b08'], [0.3, '#130d09'], [0.5, '#18110c'], [0.66, '#20160e'], [0.8, '#2d1d10'], [0.92, '#432914'], [1, '#6a421c']],
    lit: [255, 184, 100], litMin: 0.05, litMax: 0.44,
    shade: 'rgba(0,0,0,0.5)',
    index: 'rgba(255,215,170,0.07)', indexW: 0.9,
    shift: 0.8, sun: +1,
  },
  night: {
    bg: '#050202',
    water: '#030101',
    shore: 'rgba(216,86,58,0.18)',
    ramp: [[0, '#060202'], [0.4, '#080303'], [0.7, '#0d0403'], [0.9, '#170604'], [1, '#240905']],
    lit: [216, 86, 58], litMin: 0.03, litMax: 0.2,
    shade: 'rgba(0,0,0,0.55)',
    index: 'rgba(216,86,58,0.08)', indexW: 0.9,
    shift: 0.8, sun: +1,
  },
};

const slim = (d) => d.replace(/(\d+)\.(\d)/g, (m, a, b) => (b === '0' ? a : `${a}.${b}`));

function reliefSVG(T, theme, scale, name) {
  const P = PAL[theme];
  const W = Math.round(T.width * scale), H = Math.round(T.height * scale);
  // Hairline widths are tuned in map units at the original resolution, so
  // they read the same whatever the raster scale.
  const ref = name === 'route' ? 2.5 : 4;
  const levels = T.layers.map((l) => l.level);
  const lo = Math.min(...levels.filter((l) => l > 0)), hi = Math.max(...levels);
  const sy = P.sun * P.shift;
  const idxEvery = name === 'route' ? 600 : 300;
  const isIndex = (lv) => lv > 0 && (lv - (name === 'route' ? 100 : 1900)) % idxEvery === 0;
  const defs = [], body = [], index = [];
  // The lake basin, in eastside units: the 1,900–1,960 m band inside this
  // ellipse is water (outside it, that band is dry valley floor).
  const monoC = [121, 150];

  T.layers.forEach((l, i) => {
    const id = `L${i}`;
    defs.push(`<path id="${id}" d="${slim(l.d)}"/>`);
    const t = Math.max(0, (l.level - lo) / (hi - lo || 1));
    const fill = ramp(P.ramp, t);
    const a = (P.litMin + (P.litMax - P.litMin) * Math.pow(t, 1.2)).toFixed(3);
    const lit = `rgba(${P.lit.join(',')},${a})`;
    if (name === 'route' && l.level === 0) {
      // Bay shoreline: land above sea level over water.
      body.push(`<use href="#${id}" fill="${fill}"/>`);
      return;
    }
    if (name === 'eastside' && l.level === 1900) {
      // The lowest surface: water inside the lake basin, land elsewhere.
      body.push(`<use href="#${id}" fill="${fill}"/>`);
      body.push(`<g clip-path="url(#mono)"><use href="#${id}" fill="${P.water}"/></g>`);
      return;
    }
    body.push(
      `<use href="#${id}" transform="translate(0 ${sy})" fill="${lit}"/>` +
        `<use href="#${id}" transform="translate(0 ${-sy})" fill="${P.shade}"/>` +
        `<use href="#${id}" fill="${fill}"/>`,
    );
    if (name === 'route' && l.level === 1900) {
      // Mono Lake from the finer eastside contours, registered by affine.
      const e19 = east.layers.find((x) => x.level === 1900).d, e196 = east.layers.find((x) => x.level === 1960).d;
      // Water = inside 1,900 m and outside 1,960 m (a mask, so the relief
      // around the lake keeps its slivers).
      defs.push(`<mask id="lakeR" maskUnits="userSpaceOnUse" x="0" y="0" width="${T.width}" height="${T.height}"><g transform="matrix(${E2R.join(' ')})"><path d="${slim(e19)}" fill="#fff"/><path d="${slim(e196)}" fill="#000"/></g></mask>`);
      body.push(`<g clip-path="url(#monoR)"><rect x="0" y="0" width="${T.width}" height="${T.height}" fill="${P.water}" mask="url(#lakeR)"/></g>`);
    }
    if (isIndex(l.level)) index.push(`<use href="#${id}" fill="none" stroke="${P.index}" stroke-width="${(P.indexW / ref).toFixed(3)}"/>`);
  });
  // Lake shore line on the eastside map (the 1,960 m contour, inside the basin).
  if (name === 'eastside') {
    const i196 = T.layers.findIndex((x) => x.level === 1960);
    index.push(`<g clip-path="url(#mono)"><use href="#L${i196}" fill="none" stroke="${P.shore}" stroke-width="${(1.1 / ref).toFixed(3)}"/></g>`);
  }

  const base = name === 'route' ? P.water : ramp(P.ramp, 0);
  const [mx, my] = monoC;
  const rM = [mx * E2R[0] + E2R[4], my * E2R[3] + E2R[5]];
  return {
    W,
    H,
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${T.width} ${T.height}">
<defs>${defs.join('')}
<clipPath id="mono"><ellipse cx="${mx}" cy="${my}" rx="72" ry="63"/></clipPath>
<clipPath id="monoR"><ellipse cx="${rM[0].toFixed(1)}" cy="${rM[1].toFixed(1)}" rx="${(72 * E2R[0]).toFixed(1)}" ry="${(63 * E2R[3]).toFixed(1)}"/></clipPath>
</defs>
<rect x="-5" y="-5" width="${T.width + 10}" height="${T.height + 10}" fill="${base}"/>
${body.join('\n')}
${index.join('\n')}
</svg>`,
  };
}

// ---------------------------------------------------------------------------
// Rasterize in Chromium (SVG → canvas → WebP)

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || '/opt/node22/lib/node_modules/playwright/index.mjs');
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent('<!doctype html><html><body></body></html>');
const outDir = join(root, 'public/img/topo');
mkdirSync(outDir, { recursive: true });
for (const f of readdirSync(outDir)) if (/^relief-.*\.webp$/.test(f)) unlinkSync(join(outDir, f));
const Q = { light: 0.78, dark: 0.8, night: 0.8 };

for (const [name, T] of [['route', route], ['eastside', east]]) {
  for (const theme of ['light', 'dark', 'night']) {
    const k = SCALE[name][theme];
    const { svg, W, H } = reliefSVG(T, theme, k, name);
    const tiles = tileRects(name, theme).map((t) => t.px);
    const out = await page.evaluate(
      async ({ svg, W, H, q, tiles }) => {
        const url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' }));
        const img = new Image();
        img.src = url;
        await img.decode();
        const c = document.createElement('canvas');
        c.width = W;
        c.height = H;
        c.getContext('2d').drawImage(img, 0, 0, W, H);
        URL.revokeObjectURL(url);
        return tiles.map(([x, y, w, h]) => {
          const t = document.createElement('canvas');
          t.width = w;
          t.height = h;
          t.getContext('2d').drawImage(c, x, y, w, h, 0, 0, w, h);
          return t.toDataURL('image/webp', q).split(',')[1];
        });
      },
      { svg, W, H, q: Q[theme], tiles },
    );
    out.forEach((b64, i) => {
      const buf = Buffer.from(b64, 'base64');
      writeFileSync(join(outDir, `relief-${name}-${theme}-${i}.webp`), buf);
      console.log(`wrote relief-${name}-${theme}-${i}.webp  ${tiles[i][2]}×${tiles[i][3]}  ${(buf.length / 1024).toFixed(0)} KB`);
    });
  }
}
await browser.close();
