// Generated by scripts/update-conditions.mjs. Do not edit by hand.
export const conditions = {
  "retrieved": "2026-09-27T16:16:14.751Z",
  "forecasts": [
    {
      "place": "Mammoth Lakes",
      "onTrip": false,
      "updated": "2026-09-27T13:41:03+00:00",
      "periods": [
        {
          "name": "Today",
          "temp": "60°F",
          "wind": "10 to 15 mph SW",
          "text": "Sunny",
          "detail": "Sunny. High near 60, with temperatures falling to around 52 in the afternoon. Southwest wind 10 to 15 mph, with gusts as high as 40 mph."
        },
        {
          "name": "Tonight",
          "temp": "35°F",
          "wind": "0 to 15 mph SW",
          "text": "Mostly Clear then Slight Chance Rain And Snow Showers",
          "detail": "A slight chance of rain and snow showers after 5am. Mostly clear, with a low around 35. Southwest wind 0 to 15 mph, with gusts as high as 40 mph. Chance of precipitation is 20%."
        },
        {
          "name": "Monday",
          "temp": "54°F",
          "wind": "0 to 10 mph NW",
          "text": "Chance Rain And Snow Showers then Chance Showers And Thunderstorms",
          "detail": "A chance of rain and snow showers before 11am, then a chance of showers and thunderstorms between 11am and 2pm, then a slight chance of showers and thunderstorms between 2pm and 5pm. Mostly sunny, with a high near 54. Northwest wind 0 to 10 mph, with gusts as high as 30 mph. Chance of precipitation is 40%."
        },
        {
          "name": "Monday Night",
          "temp": "35°F",
          "wind": "5 to 15 mph N",
          "text": "Mostly Clear",
          "detail": "Mostly clear, with a low around 35. North wind 5 to 15 mph, with gusts as high as 40 mph."
        },
        {
          "name": "Tuesday",
          "temp": "64°F",
          "wind": "5 mph N",
          "text": "Sunny",
          "detail": "Sunny, with a high near 64. North wind around 5 mph, with gusts as high as 25 mph."
        },
        {
          "name": "Tuesday Night",
          "temp": "40°F",
          "wind": "0 to 5 mph N",
          "text": "Clear",
          "detail": "Clear, with a low around 40. North wind 0 to 5 mph, with gusts as high as 25 mph."
        }
      ]
    },
    {
      "place": "June Lake",
      "onTrip": false,
      "updated": "2026-09-27T13:41:03+00:00",
      "periods": [
        {
          "name": "Today",
          "temp": "64°F",
          "wind": "10 mph SW",
          "text": "Sunny",
          "detail": "Sunny, with a high near 64. Southwest wind around 10 mph, with gusts as high as 35 mph."
        },
        {
          "name": "Tonight",
          "temp": "37°F",
          "wind": "0 to 10 mph SW",
          "text": "Mostly Clear then Slight Chance Rain Showers",
          "detail": "A slight chance of rain showers after 5am. Mostly clear, with a low around 37. Southwest wind 0 to 10 mph, with gusts as high as 35 mph. Chance of precipitation is 20%."
        },
        {
          "name": "Monday",
          "temp": "58°F",
          "wind": "0 to 5 mph N",
          "text": "Chance Rain And Snow Showers",
          "detail": "A slight chance of rain showers before 8am, then a chance of rain and snow showers between 8am and 2pm. Mostly sunny, with a high near 58. North wind 0 to 5 mph, with gusts as high as 25 mph. Chance of precipitation is 40%."
        },
        {
          "name": "Monday Night",
          "temp": "37°F",
          "wind": "5 to 10 mph N",
          "text": "Mostly Clear",
          "detail": "Mostly clear, with a low around 37. North wind 5 to 10 mph, with gusts as high as 30 mph."
        },
        {
          "name": "Tuesday",
          "temp": "70°F",
          "wind": "5 mph N",
          "text": "Sunny",
          "detail": "Sunny, with a high near 70. North wind around 5 mph, with gusts as high as 20 mph."
        },
        {
          "name": "Tuesday Night",
          "temp": "43°F",
          "wind": "0 to 5 mph N",
          "text": "Clear",
          "detail": "Clear, with a low around 43. North wind 0 to 5 mph."
        }
      ]
    },
    {
      "place": "Lee Vining",
      "onTrip": false,
      "updated": "2026-09-27T13:41:03+00:00",
      "periods": [
        {
          "name": "Today",
          "temp": "64°F",
          "wind": "5 to 15 mph SW",
          "text": "Mostly Sunny",
          "detail": "Mostly sunny, with a high near 64. Southwest wind 5 to 15 mph, with gusts as high as 30 mph."
        },
        {
          "name": "Tonight",
          "temp": "34°F",
          "wind": "0 to 15 mph SW",
          "text": "Mostly Clear then Slight Chance Rain Showers",
          "detail": "A slight chance of rain showers after 5am. Mostly clear, with a low around 34. Southwest wind 0 to 15 mph, with gusts as high as 30 mph. Chance of precipitation is 20%."
        },
        {
          "name": "Monday",
          "temp": "57°F",
          "wind": "0 to 15 mph N",
          "text": "Chance Rain Showers",
          "detail": "A chance of rain showers before 2pm. Mostly sunny, with a high near 57. North wind 0 to 15 mph, with gusts as high as 25 mph. Chance of precipitation is 40%."
        },
        {
          "name": "Monday Night",
          "temp": "35°F",
          "wind": "5 to 15 mph N",
          "text": "Clear",
          "detail": "Clear, with a low around 35. North wind 5 to 15 mph, with gusts as high as 25 mph."
        },
        {
          "name": "Tuesday",
          "temp": "67°F",
          "wind": "5 mph N",
          "text": "Sunny",
          "detail": "Sunny, with a high near 67. North wind around 5 mph."
        },
        {
          "name": "Tuesday Night",
          "temp": "40°F",
          "wind": "0 to 5 mph NW",
          "text": "Clear",
          "detail": "Clear, with a low around 40. Northwest wind 0 to 5 mph."
        }
      ]
    },
    {
      "place": "Tioga Pass",
      "onTrip": false,
      "updated": "2026-09-27T15:56:31+00:00",
      "periods": [
        {
          "name": "Today",
          "temp": "52°F",
          "wind": "10 to 15 mph SW",
          "text": "Mostly Sunny",
          "detail": "Mostly sunny. High near 52, with temperatures falling to around 45 in the afternoon. Southwest wind 10 to 15 mph, with gusts as high as 30 mph."
        },
        {
          "name": "Tonight",
          "temp": "31°F",
          "wind": "0 to 10 mph S",
          "text": "Mostly Clear then Slight Chance Light Snow",
          "detail": "A slight chance of snow between 2am and 3am, then widespread frost and a chance of snow. Mostly clear, with a low around 31. Wind chill values as low as 30. South wind 0 to 10 mph, with gusts as high as 25 mph. Chance of precipitation is 40%. New snow accumulation of less than half an inch possible."
        },
        {
          "name": "Monday",
          "temp": "46°F",
          "wind": "0 to 10 mph NNE",
          "text": "Chance Light Snow then Chance Snow Showers",
          "detail": "A chance of snow before 11am, then a chance of snow showers and a slight chance of thunderstorms between 11am and 2pm, then a chance of showers and thunderstorms between 2pm and 5pm. Mostly sunny. High near 46, with temperatures falling to around 43 in the afternoon. Wind chill values as low as 25. North northeast wind 0 to 10 mph, with gusts as high as 25 mph. Chance of precipitation is 40%. New snow accumulation of less than half an inch possible."
        },
        {
          "name": "Monday Night",
          "temp": "32°F",
          "wind": "10 to 15 mph NNE",
          "text": "Mostly Clear",
          "detail": "Mostly clear, with a low around 32. Wind chill values as low as 26. North northeast wind 10 to 15 mph, with gusts as high as 30 mph."
        },
        {
          "name": "Tuesday",
          "temp": "57°F",
          "wind": "5 to 10 mph NE",
          "text": "Sunny",
          "detail": "Sunny, with a high near 57. Northeast wind 5 to 10 mph, with gusts as high as 25 mph."
        },
        {
          "name": "Tuesday Night",
          "temp": "36°F",
          "wind": "0 to 5 mph ESE",
          "text": "Clear",
          "detail": "Clear, with a low around 36. East southeast wind 0 to 5 mph."
        }
      ]
    },
    {
      "place": "Bishop",
      "onTrip": false,
      "updated": "2026-09-27T11:52:59+00:00",
      "periods": [
        {
          "name": "Today",
          "temp": "85°F",
          "wind": "5 to 16 mph S",
          "text": "Sunny",
          "detail": "Sunny. High near 85, with temperatures falling to around 81 in the afternoon. South wind 5 to 16 mph, with gusts as high as 30 mph."
        },
        {
          "name": "Tonight",
          "temp": "45°F",
          "wind": "6 to 16 mph WNW",
          "text": "Mostly Clear",
          "detail": "Mostly clear. Low around 45, with temperatures rising to around 47 overnight. West northwest wind 6 to 16 mph, with gusts as high as 29 mph."
        },
        {
          "name": "Monday",
          "temp": "73°F",
          "wind": "7 to 20 mph NW",
          "text": "Scattered Showers And Thunderstorms",
          "detail": "Isolated rain showers between 10am and 11am, then scattered showers and thunderstorms between 11am and 2pm, then isolated showers and thunderstorms. Mostly sunny. High near 73, with temperatures falling to around 71 in the afternoon. Northwest wind 7 to 20 mph, with gusts as high as 32 mph. Chance of precipitation is 40%."
        },
        {
          "name": "Monday Night",
          "temp": "43°F",
          "wind": "8 to 20 mph NNW",
          "text": "Isolated Rain Showers then Mostly Clear",
          "detail": "Isolated rain showers before 11pm. Mostly clear, with a low around 43. North northwest wind 8 to 20 mph, with gusts as high as 35 mph. Chance of precipitation is 20%."
        },
        {
          "name": "Tuesday",
          "temp": "82°F",
          "wind": "10 mph NNW",
          "text": "Sunny",
          "detail": "Sunny, with a high near 82. North northwest wind around 10 mph, with gusts as high as 18 mph."
        },
        {
          "name": "Tuesday Night",
          "temp": "47°F",
          "wind": "3 to 9 mph NW",
          "text": "Clear",
          "detail": "Clear, with a low around 47."
        }
      ]
    }
  ],
  "tioga": "Tioga Road (continuation of Highway 120 through the park) Expect 10-minute delays in Tuolumne Meadows, and 15-minute delays from 8 am to 3:30 pm, Monday through Thursday from Olmsted Pt to Tioga Pass Open Glacier Point Road Temporarily closed due to smoky conditions and to allow firefighting operations Closed Mariposa Grove Road When open, road is open only ",
  "roads": {
    "108": "SR 108 [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA] No traffic restrictions are reported for this area. [YOSEMITE NAT'L PARK] For Yosemite Nat'l Park road information call 209-372-0200",
    "120": "SR 120 [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA] No traffic restrictions are reported for this area. [YOSEMITE NAT'L PARK] For Yosenite Nat'l Park road information call 209-372-0200",
    "395": "US 395 [IN THE SOUTHERN CALIFORNIA AREA] No traffic restrictions are reported for this area. [IN THE CENTRAL CALIFORNIA AREA] Is closed to southbound traffic from Mazourka Canyohn Rd to Manzanar /in Independence/ (Inyo Co) 24 hrs a day 7 days a week thru 1700 hrs on 10/30/26 - Due to construction - Motorists are advised to use an alternate route 1-way controlled traffic at various locations from 1.5 mi north of the Jct of SR 190 to 2 mi north of the Jct of SR 190 /at Cactus Flats Rd/ (Inyo Co) - Due to emergency repairs A high wind advisory is in effect from Lone Pine to Pearsonville (Inyo Co) - Travel is not recommended for campers, trailers, or permit loads [IN THE NORTHERN CALIFORNIA AREA"
  },
  "errors": []
};
